### ISSUE TITLE
Error:(47, 17) error: void cannot be dereferenced

### ISSUE THREAD

**Issue by rexi1r** [asifmujteba/EasyVolley#1]
hi 
i got the error Error:(47, 17) error: void cannot be dereferenced in the below lines
<code>
.load(URLBase)
                .addParam("operation", "getdistinct")
                .asJsonObject()
</code>
the problem is in addparam and the return value.

**Comment by asifmujteba** [comment]
Thanks for info, i forgot to return correct object from the methods.. this has been fixed now in version#0.9.5 please update the library version and sync your project again!
Regards,
